In [3]:
import winsound as ws
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('fivethirtyeight')
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline
from bs4 import BeautifulSoup
import requests
import cv2
from sklearn.cluster import KMeans
import sklearn.utils

***
<h1>This code is the transposition of server's code.</h1>

In [4]:
alldata = pd.read_csv("dataset\\finals\\complissivolibricongenere.csv").drop(axis=1, columns=["Unnamed: 0"])
alldata

,id,book_id,authors,title,original_publication_year,average_rating,work_ratings_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,color_name,price,color,pricetag,genderid,gendernames,genderclass,discreteauthors
0,1,2767052,Suzanne Collins,"The Hunger Games (The Hunger Games, #1)",2008.0,4.34,4942365,0.013499,0.025886,0.113325,0.299716,0.547575,Black,6.83,0,2,11305.0,fantasy,4,184
1,2,3,J.K. Rowling,Harry Potter and the Sorcerer's Stone (Harry P...,1997.0,4.44,4800065,0.015730,0.021182,0.094795,0.240896,0.627396,White,49.78,1,4,11305.0,fantasy,4,43
2,3,41865,Stephenie Meyer,"Twilight (Twilight, #1)",2005.0,3.57,3916824,0.116470,0.111519,0.202541,0.223414,0.346056,Black,16.99,0,3,31745.0,vampires,6,111
3,4,2657,Harper Lee,To Kill a Mockingbird,1960.0,4.25,3340896,0.018087,0.035145,0.133747,0.299905,0.513116,Blue,16.99,4,3,18367.0,literature,10,1396
4,5,4671,F. Scott Fitzgerald,The Great Gatsby,1925.0,3.89,2773745,0.031090,0.071247,0.218534,0.337454,0.341675,Brown,17.00,8,3,18367.0,literature,10,351
5,6,11870085,John Green,The Fault in Our Stars,2012.0,4.26,2478609,0.019363,0.037409,0.132151,0.281800,0.529277,Cyan,19.99,7,3,26138.0,romance,11,297
6,7,5907,J.R.R. Tolkien,The Hobbit,1937.0,4.25,2196809,0.020950,0.034953,0.131395,0.303001,0.509702,Black,10.99,0,2,11305.0,fantasy,4,204
7,8,5107,J.D. Salinger,The Catcher in the Rye,1951.0,3.79,2120637,0.051580,0.087483,0.214578,0.311942,0.334416,Orange,15.00,9,3,33114.0,young adult,0,600
8,9,960,Dan Brown,"Angels & Demons (Robert Langdon, #1)",2000.0,3.85,2078754,0.037446,0.070109,0.220531,0.344711,0.327203,Blue,12.37,4,2,20939.0,mystery,14,239
9,10,1885,Jane Austen,Pride and Prejudice,1813.0,4.24,2191465,0.024960,0.039464,0.129982,0.278241,0.527352,White,7.52,1,2,14487.0,historical fiction,9,213
10,11,77203,Khaled Hosseini,The Kite Runner,2003.0,4.26,1878095,0.018257,0.031937,0.120368,0.334474,0.494965,Black,0.01,0,1,14487.0,historical fiction,9,747
11,12,13335037,Veronica Roth,"Divergent (Divergent, #1)",2011.0,4.24,2216814,0.016382,0.037382,0.139974,0.303601,0.502660,Brown,6.38,8,2,11305.0,fantasy,4,120
12,13,5470,George Orwell,1984,1949.0,4.14,2053394,0.020378,0.042089,0.158213,0.337013,0.442306,White,9.99,1,2,11743.0,fiction,1,241
13,14,7613,George Orwell,Animal Farm,1945.0,3.87,1982987,0.033714,0.068153,0.218575,0.352318,0.327240,Brown,14.00,8,2,11305.0,fantasy,4,241
14,15,48855,Anne Frank,The Diary of a Young Girl,1947.0,4.10,2024493,0.022339,0.045083,0.175726,0.324461,0.432391,Black,6.97,0,2,14467.0,historical,21,1326
15,16,2429135,Stieg Larsson,"The Girl with the Dragon Tattoo (Millennium, #1)",2005.0,4.11,1929834,0.028414,0.044590,0.147895,0.345877,0.433224,Violet,29.95,6,3,20939.0,mystery,14,589
16,17,6148028,Suzanne Collins,"Catching Fire (The Hunger Games, #2)",2009.0,4.30,1988079,0.005277,0.024159,0.131791,0.345679,0.493094,Brown,18.99,8,3,11305.0,fantasy,4,184
17,18,5,J.K. Rowling,Harry Potter and the Prisoner of Azkaban (Harr...,1999.0,4.53,1969375,0.003410,0.010365,0.084356,0.258685,0.643184,Orange,3.71,9,1,11305.0,fantasy,4,43
18,19,34,J.R.R. Tolkien,The Fellowship of the Ring (The Lord of the Ri...,1954.0,4.34,1832541,0.020753,0.030483,0.110411,0.269528,0.568824,Black,12.45,0,2,26785.0,sci fi fantasy,23,204
19,20,7260188,Suzanne Collins,"Mockingjay (The Hunger Games, #3)",2010.0,4.03,1870748,0.016113,0.059066,0.199418,0.330494,0.394909,Blue,18.99,4,3,11305.0,fantasy,4,184
20,21,2,J.K. Rowling,Harry Potter and the Order of the Phoenix (Har...,2003.0,4.46,1840548,0.005177,0.017156,0.097911,0.268630,0.611126,Brown,12.99,8,2,11305.0,fantasy,4,43
21,22,12232938,Alice Sebold,The Lovely Bones,2002.0,3.77,1661562,0.037782,0.078955,0.243565,0.351221,0.288477,White,15.97,1,3,11305.0,fantasy,4,716
22,23,15881,J.K. Rowling,Harry Potter and the Chamber of Secrets (Harry...,1998.0,4.37,1906199,0.004330,0.022165,0.127135,0.287623,0.558748,Violet,26.99,6,3,11305.0,fantasy,4,43
23,24,6,J.K. Rowling,Harry Potter and the Goblet of Fire (Harry Pot...,2000.0,4.53,1868642,0.003573,0.010815,0.081227,0.264859,0.639526,Black,12.99,0,2,11305.0,fantasy,4,43
24,25,136251,J.K. Rowling,Harry Potter and the Deathly Hallows (Harry Po...,2007.0,4.61,1847395,0.005068,0.012041,0.061517,0.207814,0.713560,Black,34.99,0,4,11305.0,fantasy,4,43
25,26,968,Dan Brown,"The Da Vinci Code (Robert Langdon, #2)",2003.0,3.79,1557292,0.045814,0.081226,0.218835,0.346292,0.307834,Brown,14.95,8,2,11743.0,fiction,1,239
26,27,1,J.K. Rowling,Harry Potter and the Half-Blood Prince (Harry ...,2005.0,4.54,1785676,0.004093,0.012049,0.076348,0.257061,0.650449,Brown,NaN,8,5,11305.0,fantasy,4,43
27,28,7624,William Golding,Lord of the Flies,1954.0,3.64,1671484,0.055507,0.095900,0.254653,0.337973,0.255968,Yellow,16.00,5,3,33114.0,young adult,0,1907
28,29,18135,William Shakespeare,Romeo and Juliet,1595.0,3.73,1672889,0.034659,0.091566,0.270594,0.310733,0.292449,Violet,5.99,6,2,26138.0,romance,11,23
29,30,8442457,Gillian Flynn,Gone Girl,2012.0,4.03,1626519,0.023900,0.049681,0.172350,0.378742,0.375327,Black,25.00,0,3,8517.0,crime,22,579
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9919,9971,12602078,Melody Anne,The Tycoon's Revenge (Baby for the Billionaire...,2011.0,3.87,17606,0.022436,0.067136,0.248665,0.344201,0.317562,Blue,NaN,4,5,26138.0,romance,11,1188
9920,9972,4984,Kurt Vonnegut Jr.,Bagombo Snuff Box,1999.0,3.72,8597,0.009073,0.063743,0.327672,0.398976,0.200535,Yellow,19.75,5,3,26837.0,science fiction,5,50
9921,9973,849380,John M. Gottman,The Seven Principles for Making Marriage Work:...,1999.0,4.19,10017,0.012579,0.033343,0.160128,0.344015,0.449935,White,1.55,1,1,27095.0,self help,65,3243
9922,9974,116494,Lois Lowry,"Anastasia Krupnik (Anastasia Krupnik, #1)",1978.0,3.89,12519,0.035147,0.048167,0.244588,0.334292,0.337807,Yellow,1.99,5,1,17124.0,kids,39,325
9923,9975,613991,David Gemmell,"The King Beyond the Gate (The Drenai Saga, #2)",1985.0,4.12,10307,0.004754,0.024158,0.190938,0.404967,0.375182,White,1.26,1,1,11305.0,fantasy,4,784
9924,9976,6351939,Maria V. Snyder,"Sea Glass (Glass, #2)",2009.0,4.00,15937,0.007404,0.041099,0.231223,0.388091,0.332183,Blue,0.10,4,1,11305.0,fantasy,4,214
9925,9977,202948,Anne Tyler,Ladder of Years,1995.0,3.72,12229,0.017499,0.069834,0.303704,0.394717,0.214245,White,0.01,1,1,11743.0,fiction,1,136
9926,9978,162332,Yukio Mishima,The Sailor Who Fell from Grace with the Sea,1963.0,3.89,10541,0.013471,0.055972,0.229011,0.431743,0.269804,White,15.00,1,3,11743.0,fiction,1,1942
9927,9979,16951,Wilbur Smith,"When the Lion Feeds (Courtney, #1)",1964.0,4.16,9581,0.006680,0.027972,0.172007,0.389521,0.403820,White,9.40,1,2,14467.0,historical,21,614
9928,9980,946899,Deeanne Gist,The Measure of a Lady,2006.0,3.94,9963,0.018769,0.061026,0.234568,0.336746,0.348891,White,6.57,1,2,14467.0,historical,21,1741
9929,9981,106312,Jeffery Deaver,"The Twelfth Card (Lincoln Rhyme, #6)",2005.0,3.98,12134,0.005934,0.032141,0.236855,0.424839,0.300231,Black,4.33,0,1,20939.0,mystery,14,175
9930,9982,12444298,Karen Marie Moning,"Feverborn (Fever, #8)",2016.0,4.18,14194,0.012611,0.036706,0.162604,0.336692,0.451388,Black,4.45,0,1,31617.0,urban fantasy,35,87
9931,9983,8539798,Kazue Kato,"Blue exorcist, Tome 2",2009.0,4.48,9859,0.003246,0.015417,0.103966,0.251445,0.625926,Black,28.00,0,3,11305.0,fantasy,4,1232
9932,9984,764165,Peter Matthiessen,The Snow Leopard,1978.0,4.12,9532,0.015212,0.042593,0.166387,0.355959,0.419849,Black,15.00,0,3,1691.0,adventure,13,3575
9933,9985,19688,Steve Perry,"Breaking Point (Tom Clancy's Net Force, #4)",2000.0,3.69,7825,0.034249,0.087412,0.300192,0.313866,0.264281,White,17.11,1,3,30358.0,thriller,15,1280
9934,9986,183092,Terri Blackstock,Night Light (Restoration #2),2006.0,4.35,8862,0.010833,0.019409,0.125818,0.299932,0.544008,White,14.99,1,2,20939.0,mystery,14,2698
9935,9987,8087038,Iris Johansen,"Chasing The Night (Eve Duncan, #11; Catherine ...",2010.0,4.12,10964,0.010306,0.030190,0.193999,0.360908,0.404597,White,27.99,1,3,20939.0,mystery,14,379
9936,9988,129237,John Rawls,A Theory of Justice,1971.0,3.91,9108,0.025692,0.066645,0.219697,0.348155,0.339811,White,36.00,1,4,23931.0,politics,67,2531
9937,9989,13489518,Quinn Loftis,"Out of the Dark (The Grey Wolves, #4)",2012.0,4.50,13614,0.005289,0.016821,0.092772,0.240928,0.644190,White,NaN,1,5,11305.0,fantasy,4,609
9938,9990,294081,Oscar Hijuelos,The Mambo Kings Play Songs of Love,1989.0,3.68,9776,0.038257,0.085516,0.275368,0.359349,0.241510,Black,12.00,0,2,11743.0,fiction,1,2557
9939,9991,101094,Ben Okri,The Famished Road,1991.0,3.73,8875,0.052394,0.091831,0.230535,0.326197,0.299042,Brown,16.95,8,3,11305.0,fantasy,4,1589
9940,9992,13616278,Miles Cameron,"The Red Knight (The Traitor Son Cycle, #1)",2012.0,4.12,10102,0.022966,0.048604,0.136112,0.367452,0.424866,Orange,3.88,9,1,11305.0,fantasy,4,2465
9941,9993,4936457,Ian Mortimer,The Time Traveller's Guide to Medieval England...,2008.0,3.99,12115,0.019480,0.043005,0.206108,0.395378,0.336030,Yellow,119.03,5,5,14552.0,history,18,3742
9942,9994,4769651,Michael Buckley,"The Everafter War (The Sisters Grimm, #7)",2009.0,4.32,12965,0.008484,0.022291,0.134593,0.307675,0.526957,Brown,16.95,8,3,11305.0,fantasy,4,285
9943,9995,15613,Herman Melville,"Billy Budd, Sailor",1924.0,3.09,12110,0.122048,0.183732,0.314203,0.246491,0.133526,White,4.95,1,1,14487.0,historical fiction,9,821
9944,9996,7130616,Ilona Andrews,"Bayou Moon (The Edge, #2)",2010.0,4.09,18856,0.005569,0.030494,0.187633,0.416843,0.359461,Black,3.67,0,1,31617.0,urban fantasy,35,91
9945,9997,208324,Robert A. Caro,"Means of Ascent (The Years of Lyndon Johnson, #2)",1990.0,4.25,12952,0.023394,0.042542,0.134111,0.261658,0.538295,White,22.00,1,3,14552.0,history,18,622
9946,9998,77431,Patrick O'Brian,The Mauritius Command,1977.0,4.35,10733,0.001025,0.010342,0.110966,0.395043,0.482624,Blue,15.95,4,3,11743.0,fiction,1,500
9947,9999,8565083,Peggy Orenstein,Cinderella Ate My Daughter: Dispatches from th...,2011.0,3.65,11994,0.022928,0.083542,0.313907,0.381607,0.198016,White,1.10,1,1,24526.0,psychology,46,3245
9948,10000,8914,John Keegan,The First World War,1998.0,4.00,9700,0.012062,0.035567,0.209381,0.426598,0.316392,White,18.00,1,3,14552.0,history,18,3678

In [5]:
userbook = pd.read_csv("dataset\\finals\\ratings_cleaned.csv")
userbook.head()

   Unnamed: 0  book_id  user_id  rating
0           0        1      314       5
1           1        1      439       3
2           2        1      588       5
3           3        1     1169       4
4           4        1     1185       4

In [6]:
userresume = pd.read_csv("dataset\\finals\\userresume.csv").drop(axis=1, columns=["Unnamed: 0"])
userresume.head()

   maincolor  maingender  mainprice  ratingpoint  user_id
0          0           4          3     1.973407    52036
1          0           4          3     0.541586    28158
2          0          10          3     1.142220    12381
3          0           4          2     0.548976    30944
4          0           4          3     0.921369    12874

***
<h1>First selection sample data</h1>
<p>Shows selection of sample book in web page.</p>

In [7]:
#singular = alldata.drop_duplicates(subset=["authors"], keep="first")
mostknown = alldata.sort_values(["work_ratings_count"],ascending= False )[alldata.work_ratings_count>100000]
authors = mostknown["authors"].value_counts().index.tolist()
firstauth = []
for au in authors:
    firstauth.append(mostknown[mostknown.authors == au].sample(frac=1)[0:3])
singular = pd.concat(firstauth)
selbooks = singular.sort_values(["work_ratings_count"],ascending= False )["book_id"][0:40]
selbooks = selbooks.sample(frac=1).values.tolist()
selbooks

[3636,
 12232938,
 22557272,
 43641,
 14050,
 48855,
 865,
 19063,
 890,
 7624,
 18135,
 7613,
 13496,
 428263,
 2429135,
 2657,
 4214,
 1934,
 13335037,
 5129,
 24178,
 7260188,
 19501,
 5907,
 10818853,
 77203,
 5107,
 5,
 30119,
 2767052,
 4671,
 11,
 5470,
 6,
 4667024,
 968,
 8442457,
 4381,
 930,
 10210]

***
<h1>User based elaboration</h1>

In [8]:
#suppose that these are the selected books: (book_id)
selectedbooks = [2767052, 3, 5907, 7260188]
selectedbooksid = []
for book in selectedbooks:
    selectedbooksid.append(alldata[alldata.book_id == book]["id"].values[0])
positives = userbook[userbook.rating >=4]
print(selectedbooksid)

[1, 2, 7, 20]

In [9]:
#now I need to compare the selected books with the most liked books by folks:
intersect = set([])
for i in range(len(selectedbooksid)):
    if(i == 0):
        intersect = set(positives[positives.book_id == selectedbooksid[0]]["user_id"])
    else:
        intersect = intersect.intersection( set(positives[positives.book_id == selectedbooksid[i]]["user_id"]) )
#these users has the same background 
intersect = list(intersect)
similusers = pd.DataFrame(data={"user_id":intersect})

In [10]:
#rating most uniform to population selection
ratingpoint= []
for userid in intersect:
    ratingpoint.append(userresume[userresume.user_id == userid]["ratingpoint"].values[0])

similusers = similusers.assign(ratingpoints = ratingpoint)
#take only 5 people
bestusers = similusers.sort_values(["ratingpoints"],ascending= True )["user_id"].values[0:3]
bestusers

array([51838, 32592,  3922], dtype=int64)

In [11]:
#now i have most similar person to my user, so I need to select books from him
bestintersect = set([])
for user in bestusers:
    if(user == bestusers[0]):
        bestintersect = set(positives[positives.user_id == user]["book_id"].values)
    else:
        bestintersect = bestintersect.intersection( set(positives[positives.user_id == user]["book_id"].values) )
    
bestintersect = list(bestintersect)
#remove the selected books
for b in selectedbooksid:
    bestintersect.remove(b)
bestintersect

[98, 4, 132, 140, 172, 45, 17, 18, 21, 23, 24, 25, 58, 27]

In [12]:
#let's see what books taste good
returndata = []
for bo in bestintersect:
    returndata.append(alldata[alldata.id == bo])
returndata = pd.concat(returndata)

returnid = returndata["book_id"].values.tolist()
returntitle = returndata[ "title"].values.tolist()
returntitle = [w.replace(',', '') for w in returntitle]
returnprice = returndata[ "price"].values.tolist()
returnauthor = returndata[ "authors"].values.tolist()
returnauthor = [w.replace(',', '') for w in returnauthor]

returnstr = ""
for i in range(len(returnid)):
    if(i !=0):
        returnstr += ","
    returnstr += str(returnid[i])+"/"+returntitle[i]+"/"+str(returnprice[i])+"/"+returnauthor[i]

print(returnstr)

5060378/The Girl Who Played with Fire (Millennium #2)/29.95/Stieg Larsson,2657/To Kill a Mockingbird/16.99/Harper Lee,3431/The Five People You Meet in Heaven/16.0/Mitch Albom,6892870/The Girl Who Kicked the Hornet's Nest (Millennium #3)/27.95/Stieg Larsson,15823480/Anna Karenina/12.95/Leo Tolstoy,4214/Life of Pi/nan/Yann Martel,6148028/Catching Fire (The Hunger Games #2)/18.99/Suzanne Collins,5/Harry Potter and the Prisoner of Azkaban (Harry Potter #3)/3.71/J.K. Rowling,2/Harry Potter and the Order of the Phoenix (Harry Potter #5)/12.99/J.K. Rowling,15881/Harry Potter and the Chamber of Secrets (Harry Potter #2)/26.99/J.K. Rowling,6/Harry Potter and the Goblet of Fire (Harry Potter #4)/12.99/J.K. Rowling,136251/Harry Potter and the Deathly Hallows (Harry Potter #7)/34.99/J.K. Rowling,2956/The Adventures of Huckleberry Finn/0.1/Mark Twain,1/Harry Potter and the Half-Blood Prince (Harry Potter #6)/nan/J.K. Rowling

***
<h1>Author based elaboration</h1>

In [34]:
#get all books red by selected users
allbooksreaded = []
for user in bestusers:
    allbooksreaded.append( positives[positives.user_id == user]) 
allbooksreaded = pd.concat(allbooksreaded)


#drop the selected books
for i in selectedbooksid:
    allbooksreaded = allbooksreaded[allbooksreaded.book_id != i]

#get descriptions of all books
bookdesc = []
for book in allbooksreaded["book_id"]:
    bookdesc.append( alldata[alldata.book_id == book]) 
bookdesc = pd.concat(bookdesc)
auth = bookdesc["authors"].value_counts()
auth = auth[auth >1].index.values.tolist()

#now i get the seleced authors:
#drop the selected books
selectedauthors = []
for i in selectedbooksid:
    selectedauthors.append(alldata[alldata.id ==i]["authors"].values[0])

auth = auth + selectedauthors

auth = pd.Series(auth).drop_duplicates(keep="first").values.tolist()

#now I can clean the readed books
allbooksreaded = allbooksreaded.drop_duplicates(subset=["book_id"], keep="first")#.values.tolist()

#now put authors in userbook dataset for better selection 
aulist = []
for bid in allbooksreaded["book_id"].values.tolist():
    aulist.append(alldata[alldata.id == bid]["authors"].values[0])
allbooksreaded = allbooksreaded.assign(authors = aulist)

#select only 3 best authors' books
elabau = []
for au in auth:
    elabau.append(sklearn.utils.shuffle(allbooksreaded[allbooksreaded.authors == au])[0:3])
elabau = pd.concat(elabau)["book_id"].values.tolist()

outbook = []
for e in elabau:
    outbook.append(alldata[alldata.id == e])
outbook = pd.concat(outbook)
outbook

,id,book_id,authors,title,original_publication_year,average_rating,work_ratings_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,color_name,price,color,pricetag,genderid,gendernames,genderclass,discreteauthors
20,21,2,J.K. Rowling,Harry Potter and the Order of the Phoenix (Har...,2003.0,4.46,1840548,0.005177,0.017156,0.097911,0.268630,0.611126,Brown,12.99,8,2,11305.0,fantasy,4,43
17,18,5,J.K. Rowling,Harry Potter and the Prisoner of Azkaban (Harr...,1999.0,4.53,1969375,0.003410,0.010365,0.084356,0.258685,0.643184,Orange,3.71,9,1,11305.0,fantasy,4,43
22,23,15881,J.K. Rowling,Harry Potter and the Chamber of Secrets (Harry...,1998.0,4.37,1906199,0.004330,0.022165,0.127135,0.287623,0.558748,Violet,26.99,6,3,11305.0,fantasy,4,43
188,189,33,J.R.R. Tolkien,"The Lord of the Rings (The Lord of the Rings, ...",1955.0,4.47,436346,0.011016,0.021948,0.086060,0.244801,0.636174,Yellow,20.00,5,3,11305.0,fantasy,4,204
154,155,15241,J.R.R. Tolkien,"The Two Towers (The Lord of the Rings, #2)",1954.0,4.42,532209,0.005661,0.019286,0.104156,0.293554,0.577343,Black,2.00,0,1,11305.0,fantasy,4,204
18,19,34,J.R.R. Tolkien,The Fellowship of the Ring (The Lord of the Ri...,1954.0,4.34,1832541,0.020753,0.030483,0.110411,0.269528,0.568824,Black,12.45,0,2,26785.0,sci fi fantasy,23,204
1501,1506,1427,Paulo Coelho,The Zahir,2005.0,3.56,56047,0.047763,0.117062,0.295609,0.303138,0.236427,Brown,14.99,8,2,28384.0,spirituality,61,56
626,629,1431,Paulo Coelho,Veronika Decides to Die,1998.0,3.69,132191,0.039466,0.096262,0.266085,0.331982,0.266206,NaN,NaN,-1,5,22034.0,novels,17,56
34,35,865,Paulo Coelho,The Alchemist,1988.0,3.82,1403995,0.053309,0.088044,0.205943,0.293577,0.359127,Blue,14.99,4,2,11305.0,fantasy,4,56
1592,1597,122,Bryce Courtenay,"The Power of One (The Power of One, #1)",1989.0,4.34,60575,0.011523,0.026876,0.112489,0.307800,0.541312,White,17.00,1,3,11743.0,fiction,1,2278
16,17,6148028,Suzanne Collins,"Catching Fire (The Hunger Games, #2)",2009.0,4.30,1988079,0.005277,0.024159,0.131791,0.345679,0.493094,Brown,18.99,8,3,11305.0,fantasy,4,184

***
<h1>Tag based elaboration</h1>

In [51]:
#count the number of books red from book
bookdesc = []
for book in selectedbooksid:
    bookdesc.append( alldata[alldata.id == book]) 
bookdesc = pd.concat(bookdesc)

bookdesc = bookdesc.drop_duplicates(subset=["gendernames"], keep="first")
gender = bookdesc["gendernames"].value_counts().index.values.tolist()

gender

['fantasy']

In [60]:
allbooksreaded = []
for user in bestusers:
    allbooksreaded.append( positives[positives.user_id == user]) 
allbooksreaded = pd.concat(allbooksreaded)

for i in selectedbooksid:
    allbooksreaded = allbooksreaded[allbooksreaded.book_id != i]

bookdesc = []
for book in allbooksreaded["book_id"]:
    bookdesc.append( alldata[alldata.book_id == book]) 
bookdesc = pd.concat(bookdesc)

outbook =[]
for g in gender:
    outbook.append(bookdesc[bookdesc.gendernames == g])
outbook = pd.concat(outbook)
outbook

,id,book_id,authors,title,original_publication_year,average_rating,work_ratings_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,color_name,price,color,pricetag,genderid,gendernames,genderclass,discreteauthors
17,18,5,J.K. Rowling,Harry Potter and the Prisoner of Azkaban (Harr...,1999.0,4.53,1969375,0.003410,0.010365,0.084356,0.258685,0.643184,Orange,3.71,9,1,11305.0,fantasy,4,43
3261,3275,8,J.K. Rowling,"Harry Potter Boxed Set, Books 1-5 (Harry Potte...",2003.0,4.77,33424,0.009484,0.006971,0.029260,0.110280,0.844004,White,24.69,1,3,11305.0,fantasy,4,43
3738,3753,10,J.K. Rowling,"Harry Potter Collection (Harry Potter, #1-6)",2005.0,4.73,26274,0.007726,0.007079,0.036005,0.148093,0.801096,White,46.96,1,4,11305.0,fantasy,4,43
188,189,33,J.R.R. Tolkien,"The Lord of the Rings (The Lord of the Rings, ...",1955.0,4.47,436346,0.011016,0.021948,0.086060,0.244801,0.636174,Yellow,20.00,5,3,11305.0,fantasy,4,204
4212,4229,36,Chris Smith,The Lord of the Rings: Weapons and Warfare,NaN,4.53,18911,0.015705,0.014912,0.082280,0.197927,0.689176,White,1.24,1,1,11305.0,fantasy,4,3535
3217,3230,119,Gary Russell,The Lord of the Rings: The Art of The Fellowsh...,2002.0,4.59,24412,0.008643,0.009012,0.071727,0.205268,0.705350,White,35.00,1,4,11305.0,fantasy,4,2778
1,2,3,J.K. Rowling,Harry Potter and the Sorcerer's Stone (Harry P...,1997.0,4.44,4800065,0.015730,0.021182,0.094795,0.240896,0.627396,White,49.78,1,4,11305.0,fantasy,4,43
3261,3275,8,J.K. Rowling,"Harry Potter Boxed Set, Books 1-5 (Harry Potte...",2003.0,4.77,33424,0.009484,0.006971,0.029260,0.110280,0.844004,White,24.69,1,3,11305.0,fantasy,4,43
3738,3753,10,J.K. Rowling,"Harry Potter Collection (Harry Potter, #1-6)",2005.0,4.73,26274,0.007726,0.007079,0.036005,0.148093,0.801096,White,46.96,1,4,11305.0,fantasy,4,43
188,189,33,J.R.R. Tolkien,"The Lord of the Rings (The Lord of the Rings, ...",1955.0,4.47,436346,0.011016,0.021948,0.086060,0.244801,0.636174,Yellow,20.00,5,3,11305.0,fantasy,4,204
4212,4229,36,Chris Smith,The Lord of the Rings: Weapons and Warfare,NaN,4.53,18911,0.015705,0.014912,0.082280,0.197927,0.689176,White,1.24,1,1,11305.0,fantasy,4,3535
2482,2491,117,Frank Herbert,Heretics of Dune (Dune Chronicles #5),1984.0,3.83,43369,0.016486,0.070027,0.269155,0.350757,0.293574,White,6.46,1,2,11305.0,fantasy,4,274
558,561,378,Norton Juster,The Phantom Tollbooth,1961.0,4.22,185392,0.015362,0.037337,0.150589,0.303341,0.493371,White,NaN,1,5,11305.0,fantasy,4,1868
78,79,1381,Homer,The Odyssey,-720.0,3.73,710757,0.041791,0.092337,0.257587,0.315326,0.292959,Orange,17.00,9,3,11305.0,fantasy,4,714