In [187]:
import winsound as ws
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('fivethirtyeight')
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline
from bs4 import BeautifulSoup
import requests
import cv2
from sklearn.cluster import KMeans
from multiprocessing import Pool

In [188]:
userbook = pd.read_csv("dataset\\ratings.csv")
userbook.head()
#remember: book_id equals id in books.csv

   book_id  user_id  rating
0        1      314       5
1        1      439       3
2        1      588       5
3        1     1169       4
4        1     1185       4

In [189]:
complessivo = pd.read_csv("dataset\\new\\complissivolibricongenere.csv")
complessivo = complessivo.drop(axis = 1, columns=["Unnamed: 0"])
complessivo

,id,book_id,authors,title,original_publication_year,average_rating,work_ratings_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,color_name,price,color,pricetag,genderid,gendernames,genderclass
0,1,2767052,Suzanne Collins,"The Hunger Games (The Hunger Games, #1)",2008.0,4.34,4942365,0.013499,0.025886,0.113325,0.299716,0.547575,Black,6.83,0,2,11305.0,fantasy,4
1,2,3,"J.K. Rowling, Mary GrandPr√©",Harry Potter and the Sorcerer's Stone (Harry P...,1997.0,4.44,4800065,0.015730,0.021182,0.094795,0.240896,0.627396,White,49.78,1,4,11305.0,fantasy,4
2,3,41865,Stephenie Meyer,"Twilight (Twilight, #1)",2005.0,3.57,3916824,0.116470,0.111519,0.202541,0.223414,0.346056,Black,16.99,0,3,31745.0,vampires,6
3,4,2657,Harper Lee,To Kill a Mockingbird,1960.0,4.25,3340896,0.018087,0.035145,0.133747,0.299905,0.513116,Blue,16.99,4,3,18367.0,literature,10
4,5,4671,F. Scott Fitzgerald,The Great Gatsby,1925.0,3.89,2773745,0.031090,0.071247,0.218534,0.337454,0.341675,Brown,17.00,8,3,18367.0,literature,10
5,6,11870085,John Green,The Fault in Our Stars,2012.0,4.26,2478609,0.019363,0.037409,0.132151,0.281800,0.529277,Cyan,19.99,7,3,26138.0,romance,11
6,7,5907,J.R.R. Tolkien,The Hobbit,1937.0,4.25,2196809,0.020950,0.034953,0.131395,0.303001,0.509702,Black,10.99,0,2,11305.0,fantasy,4
7,8,5107,J.D. Salinger,The Catcher in the Rye,1951.0,3.79,2120637,0.051580,0.087483,0.214578,0.311942,0.334416,Orange,15.00,9,3,33114.0,young adult,0
8,9,960,Dan Brown,"Angels & Demons (Robert Langdon, #1)",2000.0,3.85,2078754,0.037446,0.070109,0.220531,0.344711,0.327203,Blue,12.37,4,2,20939.0,mystery,14
9,10,1885,Jane Austen,Pride and Prejudice,1813.0,4.24,2191465,0.024960,0.039464,0.129982,0.278241,0.527352,White,7.52,1,2,14487.0,historical fiction,9
10,11,77203,Khaled Hosseini,The Kite Runner,2003.0,4.26,1878095,0.018257,0.031937,0.120368,0.334474,0.494965,Black,0.01,0,1,14487.0,historical fiction,9
11,12,13335037,Veronica Roth,"Divergent (Divergent, #1)",2011.0,4.24,2216814,0.016382,0.037382,0.139974,0.303601,0.502660,Brown,6.38,8,2,11305.0,fantasy,4
12,13,5470,"George Orwell, Erich Fromm, Cel√¢l √úster",1984,1949.0,4.14,2053394,0.020378,0.042089,0.158213,0.337013,0.442306,White,9.99,1,2,11743.0,fiction,1
13,14,7613,George Orwell,Animal Farm,1945.0,3.87,1982987,0.033714,0.068153,0.218575,0.352318,0.327240,Brown,14.00,8,2,11305.0,fantasy,4
14,15,48855,"Anne Frank, Eleanor Roosevelt, B.M. Mooyaart-D...",The Diary of a Young Girl,1947.0,4.10,2024493,0.022339,0.045083,0.175726,0.324461,0.432391,Black,6.97,0,2,14467.0,historical,21
15,16,2429135,"Stieg Larsson, Reg Keeland","The Girl with the Dragon Tattoo (Millennium, #1)",2005.0,4.11,1929834,0.028414,0.044590,0.147895,0.345877,0.433224,Violet,29.95,6,3,20939.0,mystery,14
16,17,6148028,Suzanne Collins,"Catching Fire (The Hunger Games, #2)",2009.0,4.30,1988079,0.005277,0.024159,0.131791,0.345679,0.493094,Brown,18.99,8,3,11305.0,fantasy,4
17,18,5,"J.K. Rowling, Mary GrandPr√©, Rufus Beck",Harry Potter and the Prisoner of Azkaban (Harr...,1999.0,4.53,1969375,0.003410,0.010365,0.084356,0.258685,0.643184,Orange,3.71,9,1,11305.0,fantasy,4
18,19,34,J.R.R. Tolkien,The Fellowship of the Ring (The Lord of the Ri...,1954.0,4.34,1832541,0.020753,0.030483,0.110411,0.269528,0.568824,Black,12.45,0,2,26785.0,sci fi fantasy,23
19,20,7260188,Suzanne Collins,"Mockingjay (The Hunger Games, #3)",2010.0,4.03,1870748,0.016113,0.059066,0.199418,0.330494,0.394909,Blue,18.99,4,3,11305.0,fantasy,4
20,21,2,"J.K. Rowling, Mary GrandPr√©",Harry Potter and the Order of the Phoenix (Har...,2003.0,4.46,1840548,0.005177,0.017156,0.097911,0.268630,0.611126,Brown,12.99,8,2,11305.0,fantasy,4
21,22,12232938,Alice Sebold,The Lovely Bones,2002.0,3.77,1661562,0.037782,0.078955,0.243565,0.351221,0.288477,White,15.97,1,3,11305.0,fantasy,4
22,23,15881,"J.K. Rowling, Mary GrandPr√©",Harry Potter and the Chamber of Secrets (Harry...,1998.0,4.37,1906199,0.004330,0.022165,0.127135,0.287623,0.558748,Violet,26.99,6,3,11305.0,fantasy,4
23,24,6,"J.K. Rowling, Mary GrandPr√©",Harry Potter and the Goblet of Fire (Harry Pot...,2000.0,4.53,1868642,0.003573,0.010815,0.081227,0.264859,0.639526,Black,12.99,0,2,11305.0,fantasy,4
24,25,136251,"J.K. Rowling, Mary GrandPr√©",Harry Potter and the Deathly Hallows (Harry Po...,2007.0,4.61,1847395,0.005068,0.012041,0.061517,0.207814,0.713560,Black,34.99,0,4,11305.0,fantasy,4
25,26,968,Dan Brown,"The Da Vinci Code (Robert Langdon, #2)",2003.0,3.79,1557292,0.045814,0.081226,0.218835,0.346292,0.307834,Brown,14.95,8,2,11743.0,fiction,1
26,28,7624,William Golding,Lord of the Flies,1954.0,3.64,1671484,0.055507,0.095900,0.254653,0.337973,0.255968,Yellow,16.00,5,3,33114.0,young adult,0
27,29,18135,"William Shakespeare, Robert Jackson",Romeo and Juliet,1595.0,3.73,1672889,0.034659,0.091566,0.270594,0.310733,0.292449,Violet,5.99,6,2,26138.0,romance,11
28,30,8442457,Gillian Flynn,Gone Girl,2012.0,4.03,1626519,0.023900,0.049681,0.172350,0.378742,0.375327,Black,25.00,0,3,8517.0,crime,22
29,31,4667024,Kathryn Stockett,The Help,2009.0,4.45,1603545,0.006383,0.015663,0.084118,0.306043,0.587793,Orange,26.95,9,3,1642.0,adult,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4226,4616,32530,Lisa Gardner,"The Third Victim (Quincy & Rainie, #2)",2001.0,4.16,22898,0.004367,0.019565,0.181501,0.405232,0.389335,White,5.88,1,2,20994.0,mystery thriller,48
4227,4617,29154543,Michael Connelly,"The Wrong Side of Goodbye (Harry Bosch, #21; H...",2016.0,4.36,28922,0.005740,0.013588,0.092974,0.393057,0.494641,Black,29.00,0,3,8517.0,crime,22
4228,4618,8045080,David Baldacci,"Hell's Corner (Camel Club, #5)",2010.0,4.10,23793,0.007439,0.029042,0.182701,0.421132,0.359686,Black,6.72,0,2,20939.0,mystery,14
4229,4619,114206,Nora Roberts,"Key of Valor (Key Trilogy, #3)",2003.0,4.10,28735,0.005603,0.034000,0.211623,0.354620,0.394153,White,5.09,1,2,22983.0,paranormal romance,74
4230,4620,781182,"Bryan Burrough, John Helyar",Barbarians at the Gate: The Fall of RJR Nabisco,1990.0,4.22,20547,0.012021,0.026476,0.143135,0.369835,0.448533,White,16.95,1,3,14552.0,history,18
4231,4621,20706284,Ann Leckie,"Ancillary Sword (Imperial Radch, #2)",2014.0,4.03,24057,0.011390,0.037619,0.186598,0.439830,0.324562,Green,16.00,3,3,26771.0,sci fi,16
4232,4622,17689,"David Fishelson, Aaron Leichter, Max Brod, Fra...",Franz Kafka's The Castle (Dramatization),2003.0,4.07,22323,0.014425,0.039108,0.194687,0.364915,0.386866,White,59.09,1,5,23471.0,philosophy,29
4233,4624,9591398,"Catherynne M. Valente, Ana Juan",The Girl Who Circumnavigated Fairyland in a Sh...,2011.0,3.97,28746,0.040214,0.061609,0.177694,0.328254,0.392228,White,4.93,1,1,19974.0,middle grade,59
4234,4626,14781501,"James Patterson, Marshall Karp","NYPD Red (NYPD Red, #1)",2012.0,3.90,24953,0.017513,0.050575,0.245982,0.382920,0.303010,Brown,34.99,8,4,20939.0,mystery,14
4235,4627,30068,"Douglas Preston, Lincoln Child","The Book of the Dead (Pendergast, #7; Diogenes...",2006.0,4.13,25369,0.005952,0.028263,0.174623,0.410343,0.380819,White,25.95,1,3,20939.0,mystery,14
4236,4628,14897790,Timur Vermes,Er ist wieder da,2012.0,3.44,23050,0.044512,0.126074,0.331150,0.342473,0.155792,White,27.47,1,3,15048.0,humor,36
4237,4629,12617758,Chris Pavone,The Expats,2012.0,3.42,24618,0.032009,0.121415,0.364368,0.356893,0.125315,Red,26.00,2,3,20994.0,mystery thriller,48
4238,4630,128752,Kathy Reichs,"Bare Bones (Temperance Brennan, #6)",2003.0,3.95,28777,0.009209,0.033812,0.249991,0.407026,0.299962,White,9.86,1,2,20939.0,mystery,14
4239,4631,16131025,Elin Hilderbrand,Beautiful Day,2013.0,3.75,22173,0.013846,0.061155,0.301763,0.408154,0.215081,Cyan,28.00,7,3,26138.0,romance,11
4240,4632,85958,"Tim LaHaye, Jerry B. Jenkins","The Indwelling (Left Behind, #7)",2000.0,3.97,22956,0.022696,0.059026,0.218505,0.322312,0.377461,Black,14.99,0,2,7077.0,christian,55
4241,4633,206682,Jeff Lindsay,"Dexter in the Dark (Dexter, #3)",2006.0,3.49,25629,0.038472,0.128838,0.332163,0.305864,0.194662,White,23.95,1,3,14821.0,horror,43
4242,4634,16634,"Hermann Hesse, Richard Winston, Clara Winston,...",The Glass Bead Game,1943.0,4.11,23461,0.020630,0.052598,0.167043,0.311410,0.448318,White,20.00,1,3,18367.0,literature,10
4243,4635,13366259,Kevin Powers,The Yellow Birds,2012.0,3.74,20074,0.025306,0.081050,0.265567,0.383282,0.244794,Orange,24.99,9,3,32130.0,war,41
4244,4636,85418,Harlan Coben,Just One Look,2004.0,4.00,25109,0.005815,0.031503,0.217173,0.446334,0.299176,Black,6.57,0,2,20994.0,mystery thriller,48
4245,4638,48132,"Gerald Durrell, Helma Lapi≈Üa","My Family and Other Animals (Corfu Trilogy, #1)",1956.0,4.27,23944,0.010817,0.030864,0.133896,0.330312,0.494111,Black,16.00,0,3,15048.0,humor,36
4246,4639,174403,Tawni O'Dell,Back Roads,1999.0,3.72,22013,0.024304,0.074093,0.294553,0.366965,0.240085,White,15.00,1,3,11743.0,fiction,1
4247,4640,11449,Raymond Carver,Cathedral,1983.0,4.30,20952,0.009355,0.025773,0.120609,0.347365,0.496898,Brown,16.00,8,3,27669.0,short stories,49
4248,4642,11574,"Stephen King, Robin A.H. Waterfield",The Body,1982.0,4.26,25271,0.004867,0.023228,0.148312,0.354636,0.468957,Black,177.26,0,5,27669.0,short stories,49
4249,4643,1999475,Donald Miller,A Million Miles in a Thousand Years: What I Le...,2009.0,4.18,20299,0.012267,0.037391,0.155082,0.351889,0.443372,White,19.99,1,3,19733.0,memoir,20
4250,4644,7992995,Alison Goodman,"Eona: The Last Dragoneye (Eon, #2)",2011.0,4.12,31455,0.016563,0.046257,0.174726,0.328215,0.434239,White,1.00,1,1,11305.0,fantasy,4
4251,4645,14570,Louisa May Alcott,"Eight Cousins (Eight Cousins, #1)",1874.0,4.02,29751,0.017983,0.043125,0.216127,0.349635,0.373130,Brown,5.99,8,2,6857.0,children,24
4252,4646,590552,Maurice Sendak,Chicken Soup with Rice: A Book of Months (The ...,1962.0,4.25,25701,0.011712,0.032645,0.165130,0.271040,0.519474,White,5.95,1,2,17124.0,kids,39
4253,4647,64862,Sue Grafton,"R is for Ricochet (Kinsey Millhone, #18)",2004.0,3.96,26079,0.006135,0.030216,0.260478,0.401166,0.302005,White,0.25,1,1,20939.0,mystery,14
4254,4649,99296,"Doreen Cronin, Harry Bliss",Diary of a Worm,1996.0,4.19,23423,0.013747,0.042138,0.171028,0.281732,0.491355,White,16.99,1,3,17124.0,kids,39
4255,4650,222576,Susan Cooper,"The Grey King (The Dark Is Rising, #4)",1975.0,4.18,29999,0.008867,0.026601,0.173939,0.352845,0.437748,White,9.88,1,2,11305.0,fantasy,4

In [190]:
userbook["book_id"].max() #proves that book_id in ratings.csv is id in books.csv!!!!!!!!!!!!!!

10000

In [192]:
#only positive reviews
positives = userbook.where(userbook["rating"] >= 4).dropna()
negatives = userbook.where(userbook["rating"] < 4).dropna()

In [193]:
#merge the informations aboute the books
list_id = complessivo["id"].values.tolist()
genders = complessivo["genderclass"].values.tolist()
prices = complessivo["pricetag"].values.tolist()
colours = complessivo["color"].values.tolist()
avgratings = complessivo["average_rating"].values.tolist()
list_genderclass = []
for i in range(len(list_id)):
    t = userbook[userbook.book_id == list_id[i]]
    t = t.assign(genderclass = lambda x: genders[i])
    t = t.assign(priceclass = lambda x: prices[i])
    t = t.assign(colorclass = lambda x: colours[i])
    t = t.assign(avgrating = lambda x: avgratings[i])
    list_genderclass.append(t)
userbook = pd.concat(list_genderclass)

In [194]:
#select only users that realy reads
axes = userbook["user_id"].value_counts().axes[0].tolist()
values = userbook["user_id"].value_counts().values.tolist()
tocatch =[]
for i in range(len(values)):
    if(values[i] >= 20):#trigger the number of books 
        tocatch.append(userbook[userbook.user_id == axes[i]])
    
userbook = pd.concat(tocatch, ignore_index =True)

In [224]:
userbook.head()

,book_id,user_id,rating,genderclass,priceclass,colorclass,avgrating,differencerating
0,4,12381,5,10,3,4,4.25,0.75
1,5,12381,4,10,3,8,3.89,0.11
2,7,12381,5,4,2,0,4.25,0.75
3,8,12381,3,0,3,9,3.79,0.79
4,10,12381,5,9,2,1,4.24,0.76

In [196]:
#set the rating difference 
userbook = userbook.assign(differencerating = abs(userbook["rating"]-userbook["avgrating"]))

In [197]:
#users classifications
userbook.sort_values(["user_id"],ascending= True )
userslist = userbook["user_id"].drop_duplicates(keep="first").values.tolist()
users = pd.DataFrame(columns = ["user_id", "ratingpoint", "maincolor", "mainprice", "maingender"])
listnewusers = []
for user in userslist:
    usertable = userbook[userbook.user_id == user]
    point = sum(usertable["differencerating"]*usertable["differencerating"])/len(usertable["differencerating"])
    liked = usertable[usertable.rating >=4]
    if(not liked.empty):
        gender = liked["genderclass"].value_counts(sort=True, ascending=False).index[0]
    price = usertable["priceclass"].value_counts(sort=True, ascending=False).index[0]
    color = usertable["colorclass"].value_counts(sort=True, ascending=False).index[0]
    newuser = pd.DataFrame(data = {"user_id": [user], "ratingpoint": [point], "maincolor": [color], "mainprice": [price], "maingender": [gender]})
    listnewusers.append(newuser)
users = pd.concat(listnewusers, ignore_index=True)

In [215]:
users.sort_values(["ratingpoint"],ascending= True )
bestusers = users[users.ratingpoint<0.4]
bestusers[bestusers.maingender ==25]

      maincolor  maingender  mainprice  ratingpoint  user_id
2364          1          25          3     0.394851     1064
2461          1          25          2     0.386696     2432
2791          1          25          2     0.334105    52937
3461          1          25          3     0.237722    22301

In [218]:
userbook[userbook.user_id == 1064][userbook.rating>=4][userbook.genderclass==25]

,book_id,user_id,rating,genderclass,priceclass,colorclass,avgrating,differencerating
201429,808,1064,4,25,3,9,4.23,0.23
201437,1489,1064,4,25,1,1,4.19,0.19
201450,2556,1064,4,25,3,1,4.16,0.16
201463,3234,1064,4,25,2,1,4.05,0.05

In [223]:
complessivo[complessivo.id == 808]

,id,book_id,authors,title,original_publication_year,average_rating,work_ratings_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,color_name,price,color,pricetag,genderid,gendernames,genderclass
717,808,9673436,Brian Selznick,The Invention of Hugo Cabret,2007.0,4.23,135507,0.011815,0.031157,0.147756,0.331311,0.477961,Orange,24.99,9,3,6953.0,childrens,25